# template.tcl : template Tcl file generated by Liberate dev on Thu Oct 10 17:25:11 EDT 2019

set_var slew_lower_rise 0.2
set_var slew_lower_fall 0.2
set_var slew_upper_rise 0.8
set_var slew_upper_fall 0.8

set_var measure_slew_lower_rise 0.2
set_var measure_slew_lower_fall 0.2
set_var measure_slew_upper_rise 0.8
set_var measure_slew_upper_fall 0.8

set_var delay_inp_rise 0.5
set_var delay_inp_fall 0.5
set_var delay_out_rise 0.5
set_var delay_out_fall 0.5

set_var def_arc_msg_level 0
set_var process_match_pins_to_ports 1
set_var max_transition 3e-10
set_var min_transition 1e-11
set_var min_output_cap 1e-15

set cells { \
  addf_1x \
  addh_1x \
  and2_1x \
  and2_2x \
  and2_4x \
  and3_1x \
  and3_2x \
  and3_4x \
  ao21_1x \
  ao21_2x \
  ao21_4x \
  ao22_1x \
  ao22_2x \
  ao22_4x \
  aoi21_1x \
  aoi21_2x \
  aoi21_4x \
  aoi22_1x \
  aoi22_2x \
  aoi22_4x \
  buf_16x \
  buf_1x \
  buf_2x \
  buf_32x \
  buf_4x \
  buf_6x \
  buf_8x \
  decap_2x \
  decap_3x \
  decap_4x \
  decap_8x \
  dffnq_1x \
  dffnsrpq_1x \
  dffq_1x \
  dffqn_1x \
  dffrq_1x \
  dffsq_1x \
  dffsrpq_1x \
  dly_1x \
  inv_12x \
  inv_16x \
  inv_1x \
  inv_2x \
  inv_32x \
  inv_4x \
  inv_6x \
  inv_8x \
  latch_1x \
  mux2_1x \
  mux2_2x \
  mux2_4x \
  muxi2_1x \
  nand2_1x \
  nand2_2x \
  nand2_4x \
  nand3_1x \
  nand3_2x \
  nand3_4x \
  nor2_1x \
  nor2_2x \
  nor2_4x \
  nor3_1x \
  nor3_2x \
  nor3_4x \
  oa21_1x \
  oa21_2x \
  oa21_4x \
  oa22_1x \
  oa22_2x \
  oa22_4x \
  oai21_1x \
  oai21_2x \
  oai21_4x \
  oai22_1x \
  oai22_2x \
  oai22_4x \
  or2_1x \
  or2_2x \
  or2_4x \
  or3_1x \
  or3_2x \
  or3_4x \
  sdffnq_1x \
  sdffq_1x \
  sdffqn_1x \
  sdffrq_1x \
  sdffsq_1x \
  tiehi_1x \
  tielo_1x \
  tinv_1x \
  tinv_2x \
  xnor2_1x \
  xnor2_2x \
  xnor2_4x \
  xor2_1x \
  xor2_2x \
  xor2_4x \
}

define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201035 0.0040415 0.00812481 0.0163337 0.0328364 0.0660125 } \
         delay_template_7x7

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201035 0.0040415 0.00812481 0.0163337 0.0328364 0.0660125 } \
         power_template_7x7

if {[ALAPI_active_cell "addf_1x"]} {
define_cell \
       -input { A B CI } \
       -output { CO S } \
       -pinlist { A B CI CO S } \
       -delay delay_template_7x7 \
       -power power_template_7x7 \
       addf_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201199 0.00404811 0.00814476 0.0163872 0.0329709 0.0663371 } \
         delay_template_7x7_1

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201199 0.00404811 0.00814476 0.0163872 0.0329709 0.0663371 } \
         power_template_7x7_1

if {[ALAPI_active_cell "addh_1x"]} {
define_cell \
       -input { A B } \
       -output { CO S } \
       -pinlist { A B CO S } \
       -delay delay_template_7x7_1 \
       -power power_template_7x7_1 \
       addh_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201338 0.00405371 0.00816168 0.0164326 0.0330851 0.0666131 } \
         delay_template_7x7_2

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201338 0.00405371 0.00816168 0.0164326 0.0330851 0.0666131 } \
         power_template_7x7_2

if {[ALAPI_active_cell "and2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_2 \
       -power power_template_7x7_2 \
       and2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225912 0.0051036 0.0115296 0.0260468 0.0588427 0.132932 } \
         delay_template_7x7_3

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225912 0.0051036 0.0115296 0.0260468 0.0588427 0.132932 } \
         power_template_7x7_3

if {[ALAPI_active_cell "and2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_3 \
       -power power_template_7x7_3 \
       and2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00266866 0.00667165 0.0166791 0.0416978 0.104244 0.260611 } \
         delay_template_7x7_4

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00266866 0.00667165 0.0166791 0.0416978 0.104244 0.260611 } \
         power_template_7x7_4

if {[ALAPI_active_cell "and2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_4 \
       -power power_template_7x7_4 \
       and2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201197 0.00404801 0.00814447 0.0163864 0.0329689 0.0663323 } \
         delay_template_7x7_5

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201197 0.00404801 0.00814447 0.0163864 0.0329689 0.0663323 } \
         power_template_7x7_5

if {[ALAPI_active_cell "and3_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_5 \
       -power power_template_7x7_5 \
       and3_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225408 0.00508087 0.0114527 0.0258152 0.0581895 0.131164 } \
         delay_template_7x7_6

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225408 0.00508087 0.0114527 0.0258152 0.0581895 0.131164 } \
         power_template_7x7_6

if {[ALAPI_active_cell "and3_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_6 \
       -power power_template_7x7_6 \
       and3_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00257851 0.00644628 0.0161157 0.0402893 0.100723 0.251808 } \
         delay_template_7x7_7

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00257851 0.00644628 0.0161157 0.0402893 0.100723 0.251808 } \
         power_template_7x7_7

if {[ALAPI_active_cell "and3_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_7 \
       -power power_template_7x7_7 \
       and3_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020144 0.00405782 0.0081741 0.0164659 0.033169 0.0668158 } \
         delay_template_7x7_8

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020144 0.00405782 0.0081741 0.0164659 0.033169 0.0668158 } \
         power_template_7x7_8

if {[ALAPI_active_cell "ao21_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_8 \
       -power power_template_7x7_8 \
       ao21_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225929 0.00510439 0.0115323 0.0260548 0.0588653 0.132994 } \
         delay_template_7x7_9

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225929 0.00510439 0.0115323 0.0260548 0.0588653 0.132994 } \
         power_template_7x7_9

if {[ALAPI_active_cell "ao21_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_9 \
       -power power_template_7x7_9 \
       ao21_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00266006 0.00665016 0.0166254 0.0415635 0.103909 0.259772 } \
         delay_template_7x7_10

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00266006 0.00665016 0.0166254 0.0415635 0.103909 0.259772 } \
         power_template_7x7_10

if {[ALAPI_active_cell "ao21_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_10 \
       -power power_template_7x7_10 \
       ao21_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201401 0.00405626 0.00816936 0.0164532 0.033137 0.0667384 } \
         delay_template_7x7_11

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201401 0.00405626 0.00816936 0.0164532 0.033137 0.0667384 } \
         power_template_7x7_11

if {[ALAPI_active_cell "ao22_1x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_11 \
       -power power_template_7x7_11 \
       ao22_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225682 0.00509326 0.0114946 0.0259413 0.0585449 0.132126 } \
         delay_template_7x7_12

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225682 0.00509326 0.0114946 0.0259413 0.0585449 0.132126 } \
         power_template_7x7_12

if {[ALAPI_active_cell "ao22_2x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_12 \
       -power power_template_7x7_12 \
       ao22_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264106 0.00660266 0.0165066 0.0412666 0.103167 0.257916 } \
         delay_template_7x7_13

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264106 0.00660266 0.0165066 0.0412666 0.103167 0.257916 } \
         power_template_7x7_13

if {[ALAPI_active_cell "ao22_4x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_13 \
       -power power_template_7x7_13 \
       ao22_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0017327 0.00300225 0.005202 0.00901351 0.0156177 0.0270608 } \
         delay_template_7x7_14

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0017327 0.00300225 0.005202 0.00901351 0.0156177 0.0270608 } \
         power_template_7x7_14

if {[ALAPI_active_cell "aoi21_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_14 \
       -power power_template_7x7_14 \
       aoi21_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00194318 0.00377596 0.00733739 0.0142579 0.0277057 0.0538373 } \
         delay_template_7x7_15

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00194318 0.00377596 0.00733739 0.0142579 0.0277057 0.0538373 } \
         power_template_7x7_15

if {[ALAPI_active_cell "aoi21_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_15 \
       -power power_template_7x7_15 \
       aoi21_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00217861 0.00474633 0.0103404 0.0225277 0.049079 0.106924 } \
         delay_template_7x7_16

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00217861 0.00474633 0.0103404 0.0225277 0.049079 0.106924 } \
         power_template_7x7_16

if {[ALAPI_active_cell "aoi21_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_16 \
       -power power_template_7x7_16 \
       aoi21_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00172319 0.00296937 0.00511679 0.00881719 0.0151937 0.0261815 } \
         delay_template_7x7_17

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00172319 0.00296937 0.00511679 0.00881719 0.0151937 0.0261815 } \
         power_template_7x7_17

if {[ALAPI_active_cell "aoi22_1x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_17 \
       -power power_template_7x7_17 \
       aoi22_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192972 0.00372383 0.00718596 0.0138669 0.0267593 0.051638 } \
         delay_template_7x7_18

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192972 0.00372383 0.00718596 0.0138669 0.0267593 0.051638 } \
         power_template_7x7_18

if {[ALAPI_active_cell "aoi22_2x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_18 \
       -power power_template_7x7_18 \
       aoi22_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00216433 0.00468434 0.0101385 0.0219431 0.0474922 0.102789 } \
         delay_template_7x7_19

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00216433 0.00468434 0.0101385 0.0219431 0.0474922 0.102789 } \
         power_template_7x7_19

if {[ALAPI_active_cell "aoi22_4x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_19 \
       -power power_template_7x7_19 \
       aoi22_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.010552 0.02638 0.0659499 0.164875 0.412187 1.03047 } \
         delay_template_7x7_20

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.010552 0.02638 0.0659499 0.164875 0.412187 1.03047 } \
         power_template_7x7_20

if {[ALAPI_active_cell "buf_16x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_20 \
       -power power_template_7x7_20 \
       buf_16x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201432 0.0040575 0.00817311 0.0164633 0.0331624 0.0667997 } \
         delay_template_7x7_21

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201432 0.0040575 0.00817311 0.0164633 0.0331624 0.0667997 } \
         power_template_7x7_21

if {[ALAPI_active_cell "buf_1x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_21 \
       -power power_template_7x7_21 \
       buf_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0022625 0.00511893 0.0115816 0.0262034 0.0592853 0.134133 } \
         delay_template_7x7_22

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0022625 0.00511893 0.0115816 0.0262034 0.0592853 0.134133 } \
         power_template_7x7_22

if {[ALAPI_active_cell "buf_2x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_22 \
       -power power_template_7x7_22 \
       buf_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0193235 0.0483089 0.120772 0.30193 0.754826 1.88707 } \
         delay_template_7x7_23

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0193235 0.0483089 0.120772 0.30193 0.754826 1.88707 } \
         power_template_7x7_23

if {[ALAPI_active_cell "buf_32x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_23 \
       -power power_template_7x7_23 \
       buf_32x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00273017 0.00682541 0.0170635 0.0426588 0.106647 0.266618 } \
         delay_template_7x7_24

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00273017 0.00682541 0.0170635 0.0426588 0.106647 0.266618 } \
         power_template_7x7_24

if {[ALAPI_active_cell "buf_4x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_24 \
       -power power_template_7x7_24 \
       buf_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00409679 0.010242 0.0256049 0.0640123 0.160031 0.400077 } \
         delay_template_7x7_25

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00409679 0.010242 0.0256049 0.0640123 0.160031 0.400077 } \
         power_template_7x7_25

if {[ALAPI_active_cell "buf_6x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_25 \
       -power power_template_7x7_25 \
       buf_6x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00541349 0.0135337 0.0338343 0.0845858 0.211464 0.528661 } \
         delay_template_7x7_26

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00541349 0.0135337 0.0338343 0.0845858 0.211464 0.528661 } \
         power_template_7x7_26

if {[ALAPI_active_cell "buf_8x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_26 \
       -power power_template_7x7_26 \
       buf_8x

}
set_var keep_dcap_leakage 1

if {[ALAPI_active_cell "decap_2x"]} {
define_cell \
       -power power_template_7x7 \
       decap_2x

}
if {[ALAPI_active_cell "decap_3x"]} {
define_cell \
       -power power_template_7x7 \
       decap_3x

}
if {[ALAPI_active_cell "decap_4x"]} {
define_cell \
       -power power_template_7x7 \
       decap_4x

}
if {[ALAPI_active_cell "decap_8x"]} {
define_cell \
       -power power_template_7x7 \
       decap_8x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201453 0.00405832 0.0081756 0.01647 0.0331792 0.0668405 } \
         delay_template_7x7_27

define_template -type constraint \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         constraint_template_7x7

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201453 0.00405832 0.0081756 0.01647 0.0331792 0.0668405 } \
         power_template_7x7_27

if {[ALAPI_active_cell "dffnq_1x"]} {
define_cell \
       -clock { CKN } \
       -input { D } \
       -output { Q } \
       -pinlist { CKN D Q } \
       -delay delay_template_7x7_27 \
       -power power_template_7x7_27 \
       -constraint constraint_template_7x7 \
       dffnq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201278 0.00405126 0.00815429 0.0164127 0.0330352 0.0664924 } \
         delay_template_7x7_28

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201278 0.00405126 0.00815429 0.0164127 0.0330352 0.0664924 } \
         power_template_7x7_28

if {[ALAPI_active_cell "dffnsrpq_1x"]} {
define_cell \
       -clock { CKN } \
       -async { R SN } \
       -input { D } \
       -output { Q } \
       -pinlist { CKN D R SN Q } \
       -delay delay_template_7x7_28 \
       -power power_template_7x7_28 \
       -constraint constraint_template_7x7 \
       dffnsrpq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201494 0.00405999 0.00818064 0.0164835 0.0332133 0.0669229 } \
         delay_template_7x7_29

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201494 0.00405999 0.00818064 0.0164835 0.0332133 0.0669229 } \
         power_template_7x7_29

if {[ALAPI_active_cell "dffq_1x"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_template_7x7_29 \
       -power power_template_7x7_29 \
       -constraint constraint_template_7x7 \
       dffq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200142 0.00400569 0.00801707 0.0160455 0.0321139 0.0642735 } \
         delay_template_7x7_30

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200142 0.00400569 0.00801707 0.0160455 0.0321139 0.0642735 } \
         power_template_7x7_30

if {[ALAPI_active_cell "dffqn_1x"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { QN } \
       -pinlist { CLK D QN } \
       -delay delay_template_7x7_30 \
       -power power_template_7x7_30 \
       -constraint constraint_template_7x7 \
       dffqn_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200945 0.0040379 0.00811398 0.0163047 0.0327635 0.0658367 } \
         delay_template_7x7_31

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200945 0.0040379 0.00811398 0.0163047 0.0327635 0.0658367 } \
         power_template_7x7_31

if {[ALAPI_active_cell "dffrq_1x"]} {
define_cell \
       -clock { CLK } \
       -async { RN } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D RN Q } \
       -delay delay_template_7x7_31 \
       -power power_template_7x7_31 \
       -constraint constraint_template_7x7 \
       dffrq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020143 0.0040574 0.00817281 0.0164625 0.0331603 0.0667947 } \
         delay_template_7x7_32

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020143 0.0040574 0.00817281 0.0164625 0.0331603 0.0667947 } \
         power_template_7x7_32

if {[ALAPI_active_cell "dffsq_1x"]} {
define_cell \
       -clock { CLK } \
       -async { SN } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D SN Q } \
       -delay delay_template_7x7_32 \
       -power power_template_7x7_32 \
       -constraint constraint_template_7x7 \
       dffsq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201338 0.00405368 0.00816158 0.0164323 0.0330844 0.0666114 } \
         delay_template_7x7_33

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201338 0.00405368 0.00816158 0.0164323 0.0330844 0.0666114 } \
         power_template_7x7_33

if {[ALAPI_active_cell "dffsrpq_1x"]} {
define_cell \
       -clock { CLK } \
       -async { R SN } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D R SN Q } \
       -delay delay_template_7x7_33 \
       -power power_template_7x7_33 \
       -constraint constraint_template_7x7 \
       dffsrpq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00176801 0.00312587 0.00552658 0.00977107 0.0172754 0.0305431 } \
         delay_template_7x7_34

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00176801 0.00312587 0.00552658 0.00977107 0.0172754 0.0305431 } \
         power_template_7x7_34

if {[ALAPI_active_cell "dly_1x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_34 \
       -power power_template_7x7_34 \
       dly_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00753182 0.0188296 0.0470739 0.117685 0.294212 0.735529 } \
         delay_template_7x7_35

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00753182 0.0188296 0.0470739 0.117685 0.294212 0.735529 } \
         power_template_7x7_35

if {[ALAPI_active_cell "inv_12x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_35 \
       -power power_template_7x7_35 \
       inv_12x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00980138 0.0245035 0.0612586 0.153147 0.382866 0.957166 } \
         delay_template_7x7_36

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00980138 0.0245035 0.0612586 0.153147 0.382866 0.957166 } \
         power_template_7x7_36

if {[ALAPI_active_cell "inv_16x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_36 \
       -power power_template_7x7_36 \
       inv_16x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00198964 0.00395868 0.00787635 0.0156711 0.0311799 0.0620368 } \
         delay_template_7x7_37

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00198964 0.00395868 0.00787635 0.0156711 0.0311799 0.0620368 } \
         power_template_7x7_37

if {[ALAPI_active_cell "inv_1x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_37 \
       -power power_template_7x7_37 \
       inv_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00223402 0.00499084 0.0111496 0.0249085 0.0556461 0.124315 } \
         delay_template_7x7_38

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00223402 0.00499084 0.0111496 0.0249085 0.0556461 0.124315 } \
         power_template_7x7_38

if {[ALAPI_active_cell "inv_2x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_38 \
       -power power_template_7x7_38 \
       inv_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0180985 0.0452463 0.113116 0.282789 0.706973 1.76743 } \
         delay_template_7x7_39

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0180985 0.0452463 0.113116 0.282789 0.706973 1.76743 } \
         power_template_7x7_39

if {[ALAPI_active_cell "inv_32x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_39 \
       -power power_template_7x7_39 \
       inv_32x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00254075 0.00635187 0.0158797 0.0396992 0.099248 0.24812 } \
         delay_template_7x7_40

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00254075 0.00635187 0.0158797 0.0396992 0.099248 0.24812 } \
         power_template_7x7_40

if {[ALAPI_active_cell "inv_4x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_40 \
       -power power_template_7x7_40 \
       inv_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00379481 0.00948701 0.0237175 0.0592938 0.148235 0.370586 } \
         delay_template_7x7_41

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00379481 0.00948701 0.0237175 0.0592938 0.148235 0.370586 } \
         power_template_7x7_41

if {[ALAPI_active_cell "inv_6x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_41 \
       -power power_template_7x7_41 \
       inv_6x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00505037 0.0126259 0.0315648 0.0789121 0.19728 0.493201 } \
         delay_template_7x7_42

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00505037 0.0126259 0.0315648 0.0789121 0.19728 0.493201 } \
         power_template_7x7_42

if {[ALAPI_active_cell "inv_8x"]} {
define_cell \
       -input { A } \
       -output { X } \
       -pinlist { A X } \
       -delay delay_template_7x7_42 \
       -power power_template_7x7_42 \
       inv_8x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200961 0.00403852 0.00811584 0.0163097 0.032776 0.0658669 } \
         delay_template_7x7_43

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200961 0.00403852 0.00811584 0.0163097 0.032776 0.0658669 } \
         power_template_7x7_43

if {[ALAPI_active_cell "latch_1x"]} {
define_cell \
       -clock { CLK } \
       -input { D } \
       -output { Q } \
       -pinlist { CLK D Q } \
       -delay delay_template_7x7_43 \
       -power power_template_7x7_43 \
       -constraint constraint_template_7x7 \
       latch_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200819 0.00403284 0.00809871 0.0162638 0.0326608 0.0655891 } \
         delay_template_7x7_44

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00200819 0.00403284 0.00809871 0.0162638 0.0326608 0.0655891 } \
         power_template_7x7_44

if {[ALAPI_active_cell "mux2_1x"]} {
define_cell \
       -input { D0 D1 S } \
       -output { X } \
       -pinlist { D0 D1 S X } \
       -delay delay_template_7x7_44 \
       -power power_template_7x7_44 \
       mux2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00224264 0.00502944 0.0112792 0.0252953 0.0567282 0.127221 } \
         delay_template_7x7_45

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00224264 0.00502944 0.0112792 0.0252953 0.0567282 0.127221 } \
         power_template_7x7_45

if {[ALAPI_active_cell "mux2_2x"]} {
define_cell \
       -input { D0 D1 S } \
       -output { X } \
       -pinlist { D0 D1 S X } \
       -delay delay_template_7x7_45 \
       -power power_template_7x7_45 \
       mux2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00247386 0.00611999 0.01514 0.0374542 0.0926565 0.229219 } \
         delay_template_7x7_46

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00247386 0.00611999 0.01514 0.0374542 0.0926565 0.229219 } \
         power_template_7x7_46

if {[ALAPI_active_cell "mux2_4x"]} {
define_cell \
       -input { D0 D1 S } \
       -output { X } \
       -pinlist { D0 D1 S X } \
       -delay delay_template_7x7_46 \
       -power power_template_7x7_46 \
       mux2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00149418 0.00223259 0.0033359 0.00498445 0.00744768 0.0111282 } \
         delay_template_7x7_47

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00149418 0.00223259 0.0033359 0.00498445 0.00744768 0.0111282 } \
         power_template_7x7_47

if {[ALAPI_active_cell "muxi2_1x"]} {
define_cell \
       -input { D0 D1 S } \
       -output { X } \
       -pinlist { D0 D1 S X } \
       -delay delay_template_7x7_47 \
       -power power_template_7x7_47 \
       muxi2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00185035 0.00342381 0.00633527 0.0117225 0.0216908 0.0401356 } \
         delay_template_7x7_48

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00185035 0.00342381 0.00633527 0.0117225 0.0216908 0.0401356 } \
         power_template_7x7_48

if {[ALAPI_active_cell "nand2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_48 \
       -power power_template_7x7_48 \
       nand2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00206966 0.00428347 0.00886532 0.0183482 0.0379744 0.0785939 } \
         delay_template_7x7_49

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00206966 0.00428347 0.00886532 0.0183482 0.0379744 0.0785939 } \
         power_template_7x7_49

if {[ALAPI_active_cell "nand2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_49 \
       -power power_template_7x7_49 \
       nand2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00232745 0.005417 0.0126078 0.0293439 0.0682963 0.158956 } \
         delay_template_7x7_50

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00232745 0.005417 0.0126078 0.0293439 0.0682963 0.158956 } \
         power_template_7x7_50

if {[ALAPI_active_cell "nand2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_50 \
       -power power_template_7x7_50 \
       nand2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00180172 0.0032462 0.00584876 0.0105378 0.0189863 0.034208 } \
         delay_template_7x7_51

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00180172 0.0032462 0.00584876 0.0105378 0.0189863 0.034208 } \
         power_template_7x7_51

if {[ALAPI_active_cell "nand3_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_51 \
       -power power_template_7x7_51 \
       nand3_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201638 0.00406579 0.00819819 0.0165307 0.0333321 0.0672103 } \
         delay_template_7x7_52

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201638 0.00406579 0.00819819 0.0165307 0.0333321 0.0672103 } \
         power_template_7x7_52

if {[ALAPI_active_cell "nand3_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_52 \
       -power power_template_7x7_52 \
       nand3_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00226094 0.00511183 0.0115575 0.0261308 0.0590801 0.133576 } \
         delay_template_7x7_53

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00226094 0.00511183 0.0115575 0.0261308 0.0590801 0.133576 } \
         power_template_7x7_53

if {[ALAPI_active_cell "nand3_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_53 \
       -power power_template_7x7_53 \
       nand3_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0017473 0.00305307 0.00533465 0.00932125 0.0162871 0.0284585 } \
         delay_template_7x7_54

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0017473 0.00305307 0.00533465 0.00932125 0.0162871 0.0284585 } \
         power_template_7x7_54

if {[ALAPI_active_cell "nor2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_54 \
       -power power_template_7x7_54 \
       nor2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00195825 0.00383475 0.00750939 0.0147053 0.0287966 0.056391 } \
         delay_template_7x7_55

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00195825 0.00383475 0.00750939 0.0147053 0.0287966 0.056391 } \
         power_template_7x7_55

if {[ALAPI_active_cell "nor2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_55 \
       -power power_template_7x7_55 \
       nor2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0021969 0.00482636 0.010603 0.0232937 0.0511739 0.112424 } \
         delay_template_7x7_56

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0021969 0.00482636 0.010603 0.0232937 0.0511739 0.112424 } \
         power_template_7x7_56

if {[ALAPI_active_cell "nor2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_56 \
       -power power_template_7x7_56 \
       nor2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00160162 0.0025652 0.00410849 0.00658026 0.0105391 0.0168797 } \
         delay_template_7x7_57

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00160162 0.0025652 0.00410849 0.00658026 0.0105391 0.0168797 } \
         power_template_7x7_57

if {[ALAPI_active_cell "nor3_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_57 \
       -power power_template_7x7_57 \
       nor3_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00179936 0.0032377 0.00582579 0.0104827 0.0188622 0.0339398 } \
         delay_template_7x7_58

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00179936 0.0032377 0.00582579 0.0104827 0.0188622 0.0339398 } \
         power_template_7x7_58

if {[ALAPI_active_cell "nor3_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_58 \
       -power power_template_7x7_58 \
       nor3_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201364 0.00405475 0.0081648 0.016441 0.0331062 0.066664 } \
         delay_template_7x7_59

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201364 0.00405475 0.0081648 0.016441 0.0331062 0.066664 } \
         power_template_7x7_59

if {[ALAPI_active_cell "nor3_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_59 \
       -power power_template_7x7_59 \
       nor3_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020137 0.00405499 0.00816554 0.016443 0.0331112 0.0666761 } \
         delay_template_7x7_60

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020137 0.00405499 0.00816554 0.016443 0.0331112 0.0666761 } \
         power_template_7x7_60

if {[ALAPI_active_cell "oa21_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_60 \
       -power power_template_7x7_60 \
       oa21_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225833 0.00510004 0.0115175 0.0260104 0.0587399 0.132654 } \
         delay_template_7x7_61

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225833 0.00510004 0.0115175 0.0260104 0.0587399 0.132654 } \
         power_template_7x7_61

if {[ALAPI_active_cell "oa21_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_61 \
       -power power_template_7x7_61 \
       oa21_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0026515 0.00662875 0.0165719 0.0414297 0.103574 0.258936 } \
         delay_template_7x7_62

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0026515 0.00662875 0.0165719 0.0414297 0.103574 0.258936 } \
         power_template_7x7_62

if {[ALAPI_active_cell "oa21_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_62 \
       -power power_template_7x7_62 \
       oa21_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020143 0.00405741 0.00817285 0.0164626 0.0331606 0.0667954 } \
         delay_template_7x7_63

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020143 0.00405741 0.00817285 0.0164626 0.0331606 0.0667954 } \
         power_template_7x7_63

if {[ALAPI_active_cell "oa22_1x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_63 \
       -power power_template_7x7_63 \
       oa22_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225738 0.00509576 0.0115031 0.0259668 0.0586169 0.13232 } \
         delay_template_7x7_64

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225738 0.00509576 0.0115031 0.0259668 0.0586169 0.13232 } \
         power_template_7x7_64

if {[ALAPI_active_cell "oa22_2x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_64 \
       -power power_template_7x7_64 \
       oa22_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264668 0.0066167 0.0165417 0.0413544 0.103386 0.258465 } \
         delay_template_7x7_65

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264668 0.0066167 0.0165417 0.0413544 0.103386 0.258465 } \
         power_template_7x7_65

if {[ALAPI_active_cell "oa22_4x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_65 \
       -power power_template_7x7_65 \
       oa22_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00174267 0.00303691 0.00529235 0.00922283 0.0160724 0.0280089 } \
         delay_template_7x7_66

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00174267 0.00303691 0.00529235 0.00922283 0.0160724 0.0280089 } \
         power_template_7x7_66

if {[ALAPI_active_cell "oai21_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_66 \
       -power power_template_7x7_66 \
       oai21_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192665 0.00371198 0.0071517 0.0137788 0.026547 0.0511468 } \
         delay_template_7x7_67

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192665 0.00371198 0.0071517 0.0137788 0.026547 0.0511468 } \
         power_template_7x7_67

if {[ALAPI_active_cell "oai21_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_67 \
       -power power_template_7x7_67 \
       oai21_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00219317 0.00480999 0.0105491 0.023136 0.0507411 0.111284 } \
         delay_template_7x7_68

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00219317 0.00480999 0.0105491 0.023136 0.0507411 0.111284 } \
         power_template_7x7_68

if {[ALAPI_active_cell "oai21_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_68 \
       -power power_template_7x7_68 \
       oai21_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00168841 0.00285072 0.00481317 0.0081266 0.013721 0.0231666 } \
         delay_template_7x7_69

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00168841 0.00285072 0.00481317 0.0081266 0.013721 0.0231666 } \
         power_template_7x7_69

if {[ALAPI_active_cell "oai22_1x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_69 \
       -power power_template_7x7_69 \
       oai22_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00189274 0.00358247 0.0067807 0.0128341 0.0242917 0.0459779 } \
         delay_template_7x7_70

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00189274 0.00358247 0.0067807 0.0128341 0.0242917 0.0459779 } \
         power_template_7x7_70

if {[ALAPI_active_cell "oai22_2x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_70 \
       -power power_template_7x7_70 \
       oai22_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00212855 0.0045307 0.00964381 0.0205273 0.0436932 0.093003 } \
         delay_template_7x7_71

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00212855 0.0045307 0.00964381 0.0205273 0.0436932 0.093003 } \
         power_template_7x7_71

if {[ALAPI_active_cell "oai22_4x"]} {
define_cell \
       -input { A0 A1 B0 B1 } \
       -output { X } \
       -pinlist { A0 A1 B0 B1 X } \
       -delay delay_template_7x7_71 \
       -power power_template_7x7_71 \
       oai22_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020152 0.00406102 0.00818375 0.0164919 0.0332344 0.0669738 } \
         delay_template_7x7_72

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.0020152 0.00406102 0.00818375 0.0164919 0.0332344 0.0669738 } \
         power_template_7x7_72

if {[ALAPI_active_cell "or2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_72 \
       -power power_template_7x7_72 \
       or2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225934 0.0051046 0.011533 0.0260569 0.0588714 0.13301 } \
         delay_template_7x7_73

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225934 0.0051046 0.011533 0.0260569 0.0588714 0.13301 } \
         power_template_7x7_73

if {[ALAPI_active_cell "or2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_73 \
       -power power_template_7x7_73 \
       or2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264843 0.00662107 0.0165527 0.0413817 0.103454 0.258636 } \
         delay_template_7x7_74

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00264843 0.00662107 0.0165527 0.0413817 0.103454 0.258636 } \
         power_template_7x7_74

if {[ALAPI_active_cell "or2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_74 \
       -power power_template_7x7_74 \
       or2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201277 0.00405126 0.00815426 0.0164127 0.033035 0.066492 } \
         delay_template_7x7_75

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00201277 0.00405126 0.00815426 0.0164127 0.033035 0.066492 } \
         power_template_7x7_75

if {[ALAPI_active_cell "or3_1x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_75 \
       -power power_template_7x7_75 \
       or3_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225593 0.00508921 0.0114809 0.0259001 0.0584286 0.131811 } \
         delay_template_7x7_76

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00225593 0.00508921 0.0114809 0.0259001 0.0584286 0.131811 } \
         power_template_7x7_76

if {[ALAPI_active_cell "or3_2x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_76 \
       -power power_template_7x7_76 \
       or3_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00261435 0.00653587 0.0163397 0.0408492 0.102123 0.255307 } \
         delay_template_7x7_77

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00261435 0.00653587 0.0163397 0.0408492 0.102123 0.255307 } \
         power_template_7x7_77

if {[ALAPI_active_cell "or3_4x"]} {
define_cell \
       -input { A B C } \
       -output { X } \
       -pinlist { A B C X } \
       -delay delay_template_7x7_77 \
       -power power_template_7x7_77 \
       or3_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193472 0.00374314 0.00724191 0.0140111 0.0271075 0.0524453 } \
         delay_template_7x7_78

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193472 0.00374314 0.00724191 0.0140111 0.0271075 0.0524453 } \
         power_template_7x7_78

if {[ALAPI_active_cell "sdffnq_1x"]} {
define_cell \
       -clock { CKN } \
       -input { D SDI SEN } \
       -output { Q } \
       -pinlist { CKN D SDI SEN Q } \
       -delay delay_template_7x7_78 \
       -power power_template_7x7_78 \
       -constraint constraint_template_7x7 \
       sdffnq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193383 0.0037397 0.00723194 0.0139853 0.0270453 0.0523009 } \
         delay_template_7x7_79

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193383 0.0037397 0.00723194 0.0139853 0.0270453 0.0523009 } \
         power_template_7x7_79

if {[ALAPI_active_cell "sdffq_1x"]} {
define_cell \
       -clock { CLK } \
       -input { D SDI SEN } \
       -output { Q } \
       -pinlist { CLK D SDI SEN Q } \
       -delay delay_template_7x7_79 \
       -power power_template_7x7_79 \
       -constraint constraint_template_7x7 \
       sdffq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192341 0.00369951 0.00711569 0.0136864 0.0263246 0.0506331 } \
         delay_template_7x7_80

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00192341 0.00369951 0.00711569 0.0136864 0.0263246 0.0506331 } \
         power_template_7x7_80

if {[ALAPI_active_cell "sdffqn_1x"]} {
define_cell \
       -clock { CLK } \
       -input { D SDI SEN } \
       -output { QN } \
       -pinlist { CLK D SDI SEN QN } \
       -delay delay_template_7x7_80 \
       -power power_template_7x7_80 \
       -constraint constraint_template_7x7 \
       sdffqn_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193122 0.00372959 0.00720264 0.0139099 0.0268629 0.0518781 } \
         delay_template_7x7_81

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193122 0.00372959 0.00720264 0.0139099 0.0268629 0.0518781 } \
         power_template_7x7_81

if {[ALAPI_active_cell "sdffrq_1x"]} {
define_cell \
       -clock { CLK } \
       -async { RN } \
       -input { D SDI SEN } \
       -output { Q } \
       -pinlist { CLK D RN SDI SEN Q } \
       -delay delay_template_7x7_81 \
       -power power_template_7x7_81 \
       -constraint constraint_template_7x7 \
       sdffrq_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193433 0.00374165 0.0072376 0.0139999 0.0270806 0.0523829 } \
         delay_template_7x7_82

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00193433 0.00374165 0.0072376 0.0139999 0.0270806 0.0523829 } \
         power_template_7x7_82

if {[ALAPI_active_cell "sdffsq_1x"]} {
define_cell \
       -clock { CLK } \
       -async { SN } \
       -input { D SDI SEN } \
       -output { Q } \
       -pinlist { CLK D SDI SEN SN Q } \
       -delay delay_template_7x7_82 \
       -power power_template_7x7_82 \
       -constraint constraint_template_7x7 \
       sdffsq_1x

}
if {[ALAPI_active_cell "tiehi_1x"]} {
define_cell \
       -output { X } \
       -pinlist { X } \
       -power power_template_7x7 \
       tiehi_1x

}
if {[ALAPI_active_cell "tielo_1x"]} {
define_cell \
       -output { X } \
       -pinlist { X } \
       -power power_template_7x7 \
       tielo_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00162535 0.00264175 0.00429376 0.00697885 0.01134301 0.01843641 } \
         delay_template_7x7_83

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00162535 0.00264175 0.00429376 0.00697885 0.01134301 0.01843641 } \
         power_template_7x7_83

if {[ALAPI_active_cell "tinv_1x"]} {
define_cell \
       -input { A EN } \
       -output { X } \
       -pinlist { A EN X } \
       -delay delay_template_7x7_83 \
       -power power_template_7x7_83 \
       tinv_1x

}
if {[ALAPI_active_cell "tinv_2x"]} {
define_cell \
       -input { A EN } \
       -output { X } \
       -pinlist { A EN X } \
       -delay delay_template_7x7_83 \
       -power power_template_7x7_83 \
       tinv_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00173342 0.00300474 0.00520848 0.00902849 0.0156502 0.0271283 } \
         delay_template_7x7_84

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00173342 0.00300474 0.00520848 0.00902849 0.0156502 0.0271283 } \
         power_template_7x7_84

if {[ALAPI_active_cell "xnor2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_84 \
       -power power_template_7x7_84 \
       xnor2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00186678 0.00348486 0.00650547 0.0121443 0.0226707 0.0423212 } \
         delay_template_7x7_85

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00186678 0.00348486 0.00650547 0.0121443 0.0226707 0.0423212 } \
         power_template_7x7_85

if {[ALAPI_active_cell "xnor2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_85 \
       -power power_template_7x7_85 \
       xnor2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00218221 0.00476206 0.0103918 0.0226772 0.0494866 0.10799 } \
         delay_template_7x7_86

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00218221 0.00476206 0.0103918 0.0226772 0.0494866 0.10799 } \
         power_template_7x7_86

if {[ALAPI_active_cell "xnor2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_86 \
       -power power_template_7x7_86 \
       xnor2_4x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00174266 0.00303685 0.00529219 0.00922246 0.0160716 0.0280072 } \
         delay_template_7x7_87

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00174266 0.00303685 0.00529219 0.00922246 0.0160716 0.0280072 } \
         power_template_7x7_87

if {[ALAPI_active_cell "xor2_1x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_87 \
       -power power_template_7x7_87 \
       xor2_1x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00195152 0.00380844 0.00743227 0.0145042 0.0283054 0.0552386 } \
         delay_template_7x7_88

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00195152 0.00380844 0.00743227 0.0145042 0.0283054 0.0552386 } \
         power_template_7x7_88

if {[ALAPI_active_cell "xor2_2x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_88 \
       -power power_template_7x7_88 \
       xor2_2x

}
define_template -type delay \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00217955 0.00475045 0.0103539 0.0225668 0.0491855 0.107202 } \
         delay_template_7x7_89

define_template -type power \
         -index_1 {0.01 0.0176273 0.0310723 0.0547723 0.0965489 0.17019 0.3 } \
         -index_2 {0.001 0.00217955 0.00475045 0.0103539 0.0225668 0.0491855 0.107202 } \
         power_template_7x7_89

if {[ALAPI_active_cell "xor2_4x"]} {
define_cell \
       -input { A B } \
       -output { X } \
       -pinlist { A B X } \
       -delay delay_template_7x7_89 \
       -power power_template_7x7_89 \
       xor2_4x

}
